#!/usr/bin/env bash
# This script generates env variables

printf "My sql root password (root): "
read -r MYSQL_ROOT_PASSWORD
if [ -z "${MYSQL_ROOT_PASSWORD}" ]
then
    MYSQL_ROOT_PASSWORD=root
fi

printf "Mysql database (symfony): "
read -r MYSQL_DB
if [ -z "${MYSQL_DB}" ]
then
    MYSQL_DB=symfony
fi

printf "Mysql user (symfony): "
read -r MYSQL_USER
if [ -z "${MYSQL_USER}" ]
then
    MYSQL_USER=symfony
fi

printf "Mysql password (symfony): "
read -r MYSQL_PASSWORD
if [ -z "${MYSQL_PASSWORD}" ]
then
    MYSQL_PASSWORD=symfony
fi

printf "User inside container ($USER): "
read -r USERI
if [ -z "${USERI}" ]
then
    USERI=$USER
fi

printf "Working directory (../): "
read -r WORKING_DIR

if [ -z "${WORKING_DIR}" ]
then
    WORKING_DIR=../
fi

echo "# Autogenerated from create.sh" > .env
echo "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}" >> .env
echo "MYSQL_DATABASE=${MYSQL_DB}" >> .env
echo "MYSQL_USER=${MYSQL_USER}" >> .env
echo "MYSQL_PASSWORD=${MYSQL_PASSWORD}" >> .env
echo "USER=${USERI}" >> .env
echo "WORKING_DIR=${WORKING_DIR}" >> .env