#!/usr/bin/env bash

echo "#Autogenerated from create.sh" > ./.env
IFS=$'\n' read -d '' -r -a settings < ./.env.dist
for i in ${settings[@]}
do
    IFS='=' read -ra setting <<< "$i"

    if [ "${setting[0]}" = USER ]
    then
        setting[1]=$USER;
    fi
    printf "${setting[0]} (${setting[1]}): "

    read -r PARAMETER;
    if [ ! -z "${PARAMETER}" ]
    then
        setting[1]=${PARAMETER}
    fi
    echo "${setting[0]}=${setting[1]}" >> ./.env
done