#!/usr/bin/env bash
echo "# Autogenerated from create.sh" > .env
echo "MYSQL_ROOT_PASSWORD=root" >> .env
echo "MYSQL_DATABASE=symfonydb" >> .env
echo "MYSQL_USER=symfony" >> .env
echo "MYSQL_PASSWORD=symfony" >> .env
echo "USER=$USER" >> .env
echo "WORKING_DIR=../" >> .env
echo "DOMAIN=symfony.dev" >> .env